### ISSUE TITLE
any prebaked Grafana dashboards for this?

### ISSUE THREAD

**Issue by tedder** [HON95/prometheus-nut-exporter#13]
HON, I'm wondering if you have a dashboard or know of one for this. There's [one listed on grafana](https://grafana.com/grafana/dashboards/11712) but it's for an old (deprecated) nut collector.

**Comment by HON95** [comment]
I've uploaded a pretty simple demo dashboard here: https://grafana.com/grafana/dashboards/14371

Not super useful or pretty, but better than nothing, I suppose.
