### ISSUE TITLE
How to get the exporter running on a Raspberry Pi?

### ISSUE THREAD

**Issue by Videothek** [HON95/prometheus-nut-exporter#14]
Hey,

i have just installed my nut-server and everything seems to work fine. I can connect to telnet and so on.

So i wanted to try the nut-exporter. I created a docker-compose file and added the new job to the prometheus.yml.

But i get how you start the exporter to scrape the data, because so far i haven´t added any ip address for my nut-server.

It would be nice if you could give me an example on how to run the exporter.

Thanks in Advance :-)

**Comment by Videothek** [comment]
Hey,

thanks for your response. I have done all steps that were shown in the ReadMe but i wasnt able to get any data in Grafana from this exporter. I also noticed that the docker-compose container exited with a code of 1. So my question is if i have done something wrong and how can i fix it? If you need more info please reach out to me. :-)

**Comment by jstewart612** [comment]
just did this manually to make it work... but...

ping.  pong?
